### ISSUE TITLE
MP3CDMaker references an unavailable commit of Libraries

### ISSUE THREAD

**Issue by mcarter00** [swisspol/Libraries#1]
running `git submodule update` in MP3CDMaker yields the following error: 

```
fatal: reference is not a tree: e4203f9f61d2546868c1274da5c7a0c56b87a737
Unable to checkout 'e4203f9f61d2546868c1274da5c7a0c56b87a737' in submodule path 'Libraries'
```

**Comment by swisspol** [comment]
Ohhhh looks like I reset the history in the project when I updated it completely and forgot MP3CDMaker had a dependency on it. Thanks for reporting this!

![image](https://cloud.githubusercontent.com/assets/627915/11804054/4b885fb0-a2b5-11e5-893d-94b5a3ee2d2f.png)

**Comment by swisspol** [comment]
I restored e4203f9f61d2546868c1274da5c7a0c56b87a737 on a new `Archived` branch.
